# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0feaf7af4faab7cd653368157c1dc42b5d3f27bd38b3bb24b96a56b25634cf06f1c2bb68c977f65f69ef96cc30e5aa139ea676203a2c46637b967fae36505cc5

test:
  secret_key_base: 13b8d6dd909023ac649d4eb2b0c7c85e82ab555cb245eb0ea4219bcff2aa1e450d3605e87ec517c6b4ffe5d2cad14f9b3764e477aa41f665d7b71c4d17dd0ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
